### ISSUE TITLE
Redirect loop with 8.1.0

### ISSUE THREAD

**Issue by ppeach** [hypery2k/owncloud#351]
On enabling this app via the application menu on 8.1.0 I started to get a redirect loop on the landing page /index.php which resolved after disabling the application from another already logged in session.

**Comment by mckaygerhard** [comment]
please provide more details: debug log, setup environment, steps to reproduce, and if possible some alternate steps that already also goes to reproduce this bug!

**Comment by mckaygerhard** [comment]
Issue also confirmed only happened with oc 8.1 by @Worst45 , but i'm still waith for @ppeach feedback setup and logs debug info.

Seems commented (for oc 8.1+ only)  on appinfo/app.php, line: `OCP\App::checkAppEnabled('storagecharts2');` solves the problem, quoted text from reporter: 
> Hello, I still have the same problem on oc 8.1, even after using the last storagecharts2 github files:

> occ command does not display anything
> the login page loops while trying to fetch index.php
> The error appears on a fresh install or after migrating from oc 8.0 to 8.1 (it worked on 8.0).

> I have no specific error logs. (but I am not in debug mode or whatever)

> EDIT:
> the error appears on appinfo/app.php, line:
> OCP\App::checkAppEnabled('storagecharts2');

> If you comment this line, everything works again. Hope it could help you.
 
> tail -f /var/log/apache2/access.log
> 192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
> 192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
> ...
> 192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)
> 192.168.21.81 - - [25/Aug/2015:15:37:27 +0200] "GET /drive/index.php HTTP/1.1" 302 -/- (-%)

> (More than 20 times) 

End of line!

**Comment by mckaygerhard** [comment]
searching at oc API checkAppEnabled() its a private method and may change without notification, i not have knowled of any public alternative, seems for oc 8.1+ are deprecated but api info sais not! http://api.owncloud.org/classes/OCP.App.html#checkAppEnabled

i think its a oc core problem please report to oc issue traker firts

**Comment by mckaygerhard** [comment]
i reopened this issue due problems are since recent commits, as refers in #348, seems the application are not activated property and the "checkAppEnabled" method redirects in a infinite loop to home.

**Comment by Uccio** [comment]
Confirmed problem in ownCloud 8.1.1

To try to fix I have updated storagecharts2 to the 2.6.2 but the home page says "Update process" ...instead of infinite redirection loops

**Comment by mckaygerhard** [comment]
please @Uccio made a clean install, see the instructions for in the wiki: https://github.com/hypery2k/owncloud/wiki/StorageCharts2-Installation-and-Usage#some-unninstall-tips

the when made a clean removal, made a clean install (so then will be a firts install)

later we cover then updgrade issues if u confirm this particular issue when "app its enabled"

**Comment by hypery2k** [comment]
can you please retry the latest nightly build?

https://martinreinhardt-online.de/jenkins/job/OwnCloud_nightly/

**Comment by MightyCreak** [comment]
I opened an issue on owncloud core. At the time I didn't know it was related to the app and not the core.
https://github.com/owncloud/core/issues/17580

**Comment by Saxfusion** [comment]
If i copy the 2.6.2 nightly to the apps folder and enable it within Apps settings and log out i do get the "upgrade to 8.1.3" window when i try to login again. Once i remove the folder again it is back to normal instantly.

**Comment by mckaygerhard** [comment]
hey @Saxfusion u must delete all the registres from database, plea follow steps in wiki for complete removal of and app here: https://github.com/hypery2k/owncloud/wiki/Update-or-removal-tips-of-and-app 
the oc mechanish of automatic updates takes changes due saves the app version in database, if something change, so oc "think" was and incomplete upgrade (how stupid right)

aftr that steps copy and enable again the app and post feedback

**Comment by hypery2k** [comment]
I've got no idea why this is happening. I hate to change every time the app with every new OC release. Thats really stupid. I think I quit developing OwnCloud apps Sorry to say,

**Comment by MightyCreak** [comment]
@hypery2k I'm pretty sure that an OC dev would be able to help you on that. You may give it a try on IRC or the mailing-list. OC is evolving pretty fast and they are apparently reshaping their app system, but it often comes with some code to change on the third party side (look at the new extension system for Firefox ;)).

**Comment by hypery2k** [comment]
I'm just not happening the time for this anymore. At the end it doesn't work out for me. Spending hours for each version is more than I want to effort for each new version. Especially when it comes to testing...

**Comment by mckaygerhard** [comment]
I agree with what @hypery2k  says, this happens when a software project is taken by companies who just want money just like oc enterprices.. if there's no more feedback around that problem with a "really clean" install this issue must be close.

**Comment by hypery2k** [comment]
feel free to open a PR with the appropriate changes

**Comment by chioubaca** [comment]
Hi, just to notice that I just installed the latest version (2.6.1) from the appstore. Installing and using it was ok unitl I logged out. When trying to load ownclouds loginpage a got a Redirection Loop Error and could not load the page anymore.

I use owncloud v.8.1.3

**Comment by mckaygerhard** [comment]
please install from nighty build and report feedback!

**Comment by sturmmoewe** [comment]
I just ran into the same problem with owncloud 8.2.1. I got ERR_TOO_MANY_REDIRECTS which disappeared after I removes the Storage Charts 2 App.
I operate multiple owncloud instances with Storage Charts 2 App enabled and the problem only occured on one site. So I analyzed it a little bit deeper and found that the problem only occurs if you restrict the access to this app and grant the access only to an owncloud usergroup.
After I removed the access restrictions for this app there is no more redirect problem in owncloud even if the Storage Charts 2 App is installed and enabled.

**Comment by mckaygerhard** [comment]
since OC groups management storage_chars_2 and many others apps started have problems.. i start to think that the real problem its the constant changes that enterprices forced to the OC project..

if any body have a code to solve the situation please made a pull request to analyse, test and then merged

**Comment by ezraholm50** [comment]
enabled the app few days back, today all of a sudden, to many redirects. Came across another issue, rm the app folder and it works again.

ubuntu 14.04
owncloud 8.2.2

**Comment by hypery2k** [comment]
sorry to say, but I don't develop the app anymore

**Comment by RealRancor** [comment]
@hypery2k If the app is not developed anymore please at least set the correct max. version to 8.1 in https://github.com/hypery2k/owncloud/blob/master/storagecharts2/src/main/php/appinfo/info.xml and upload a new archive to the appstore to avoid people installing this broken version.

**Comment by mckaygerhard** [comment]
the min version muist be 5 due i have this working perfectly in 6.X oc setup

a note around that, it seems people install this in a automatically mode, and a true administer try all the new thing in a semi-manual mode always!

**Comment by RealRancor** [comment]
You can set the min version to 1 as long as the max version is set to something sane and doesn't allow users to install the app on newer versions of oC where it is causing this seen issue here.

**Comment by mckaygerhard** [comment]
@RealRancor does this part of code in info.xml are supported for oc 5 and oc 6, due i'm pretty sure its supported for oc 7.X 
```
<dependencies>
    <owncloud min-version="5" max-version="8.0"/>
</dependencies>
```

**Comment by RealRancor** [comment]
@mckaygerhard Sorry, i'm not that familiar with that. But you can have a look at:

https://doc.owncloud.org/server/8.2/developer_manual/app/info.html
https://doc.owncloud.org/server/8.2/developer_manual/app/tutorial.html#database

where you can find the info about the app metadata.

**Comment by mckaygerhard** [comment]
i already read this, the documentation does not refers seems suported by older versions:

https://doc.owncloud.org/server/8.2/developer_manual/app/info.html#dependencies

does not contains a tag "since" versions, so a commit like that will break support for OC 5 and 6 and i used still OC 6 and works very optimun (much more faster ratehr than others 8.X)

**Comment by mckaygerhard** [comment]
as i noted does not supported, https://doc.owncloud.org/server/7.0/developer_manual/app/info.html#requiremin in 7.X so this commit will break the support for older releases and this app still work perfectly in older releases

**Comment by RealRancor** [comment]
You still can distribute different versions of the app with different metadata.

Personally i don't think that anyone should care about versions older than oc8 as they are either ond-of-life or will reach end-of-life soon.

**Comment by mckaygerhard** [comment]
distribute two apps means made mechanish for two builds, if u will mantain a pull request are welcome.. 

well in part u have right, but the fact that the "upstream" does not "take care" does not mean that others will not, currently my company will not care more hardware or ram to install OC 8.X that runs several times more slowly (i have around of 1000+/- users with 300~500 concurrently)

in other hand, this app does not work in OC 8, so users must read in apps.owncloud the comments and support before made something.. 

in any case pull request are welcome but with backguard of course

**Comment by RealRancor** [comment]
Hi,

i won't do any pull requests as i don't use this app. But i think thats is also not the problem here. The main problem is that this app is breaking newer oC installations now because it is advising a compatibility with that versions.

**Comment by mckaygerhard** [comment]
done in apps site, theres the neeed info done:
https://apps.owncloud.com/content/show.php/roundcube?content=151523
said max version to 8.1, users shoud READ before try.

the break redirection its jst due the new api cleanup, due many private methods are now deprecated, the next work must take care of that!

**Comment by RealRancor** [comment]
As written above: In recent oC versions users don't need to go to apps.owncloud.com. They just open their oC internal appstore and click "enable". 

Ah, and btw. this issue here happens with 8.1 so the max version of 8.1 is wrong

**Comment by mckaygerhard** [comment]
umm theres not are solved for 8.1? i thing was solved for 8.0 and then later for 8.1? and about the ap store, well @hypery2k then must change some of the description to mention those limits

i noted that **more great apps in the store have same problems as this.. the cause are alway the same, constants changes in OC code forces others to constants changes in apps.. i'm tyred of this** and then also too..

**Comment by RealRancor** [comment]
Just see comments like https://github.com/hypery2k/owncloud/issues/351#issuecomment-168797507 that this is still happening.
